### ISSUE TITLE
iv is very slow

### ISSUE THREAD

**Issue by emk2203** [kenshaw/iv#1]
I am using `iv` over ssh to display image files like so:

```bash
find /srv/media/completed/\!music -iname '*.webp' -exec iv {} +
```

files take a minute to get displayed. `lsix` is much faster. Is this an issue of `iv` or of the sixel protocol?

**Comment by kenshaw** [comment]
@emk2203 if `lsix` works for you, I'd suggest using it. It's a combination of Go being slow at decoding/reencoding images. I don't have any intention of trying to make `iv` run faster. It's considerably faster when used with WezTerm, Kitty, or other terminals that support non Sixel graphics.
